---
- hosts: mywebservers
  become: yes
  tasks:
  - name: Install Webserver Apache2
    apt: 
      name: apache2
      state: absent
  
    notify:
    - Restart Webserver

  handlers:
  - name: Restart Webserver
    service:
      name: apache2
      state: restarted


