---
- hosts: 10.0.0.5
  become: yes
  tasks:
  - name: Install git
    apt:
      name: git
      state: present

  - name: Install tree
    apt:
      name: tree
      statee: present
    ignore_errors: yes
    
  - name: Install wget
    apt:
      name: wget
      state: present