---
- hosts: 10.0.0.5
  become: yes
  tasks:
  - name: Download file from URL
    get_url:
      url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
      dest: /home/vamsi/apache-tomcat-10.0.20.tar.gz
      force_basic_auth: yes
