---
- name: Playbook to Install webserver on myVM-Node-UBUNTU Machine
  hosts: all
  become: yes
  tasks:
   - name: I want to install apache2 webserver on myVM-Node-UBUNTU
     apt:
       name: apache2 
       state: present

   - name: I want to Stop apache2 webserver on myVM-Node-UBUNTU
     service:
       name: apache2 
       state: started
       



      

