---
- name: Playbook to Install webserver on myVM-Node-01 Machine
  hosts: all
  become: yes
  tasks:
   - name: I want to install apache2 webserver on myVM-Node-01
     apt:
       name: apache2 
       state: present

   - name: I want to Start apache2 webserver on myVM-Node-01
     service:
       name: apache2 
       state: started



      

